//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardeningF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.OrdenCliente = new HashSet<OrdenCliente>();
            this.Direccion = new HashSet<Direccion>();
        }
    
        public int id_cliente { get; set; }
        public string nombre_cliente { get; set; }
        public string app_cliente { get; set; }
        public string apm_cliente { get; set; }
        public string correo_cliente { get; set; }
        public string telefono_cliente { get; set; }
        public string num_tdc { get; set; }
        public Nullable<int> cvv { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenCliente> OrdenCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Direccion> Direccion { get; set; }
    }
}
