//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardeningF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Direccion()
        {
            this.OrdenCliente = new HashSet<OrdenCliente>();
        }
    
        public int id_direccion { get; set; }
        public int id_cliente { get; set; }
        public string calle { get; set; }
        public byte[] colonia { get; set; }
        public string estado { get; set; }
        public string municipio { get; set; }
        public string no_exterior { get; set; }
        public Nullable<int> no_interior { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenCliente> OrdenCliente { get; set; }
    }
}
