//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardeningF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int id_empleado { get; set; }
        public string nombre_empleado { get; set; }
        public string app_empleado { get; set; }
        public string apm_empleado { get; set; }
        public string email_empleado { get; set; }
        public string rol_empleado { get; set; }
        public int id_depto { get; set; }
    
        public virtual Departamento Departamento { get; set; }
    }
}
