//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardeningF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paqueteria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paqueteria()
        {
            this.OrdenCliente = new HashSet<OrdenCliente>();
        }
    
        public int id_paqueteria { get; set; }
        public string nombre_paqueteria { get; set; }
        public string rfc_paqueteria { get; set; }
        public long telefono_paqueteria { get; set; }
        public string web_paqueteria { get; set; }
        public string direccion_paqueteria { get; set; }
        public string contacto_paqueteria { get; set; }
        public long tel_contacto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenCliente> OrdenCliente { get; set; }
    }
}
